### ISSUE TITLE
Add cookie storage fallback

### ISSUE THREAD

**Issue by Eeems** [geuis/argon#3]
I'd suggest adding cookie storage fallback (maybe as an optional piece) instead of just erroring if localStorage or sessionStorage don't exist.

**Comment by geuis** [comment]
Thanks for the suggestion. There's no modern browser that doesn't support Storage though. The glaring exception to this is Safari in private browsing mode. It disables Storage.

I'm not sure cookie fallback is really needed. Perhaps there's a more graceful way to handle it than an error. Got any ideas?

**Comment by Eeems** [comment]
You could always load in a polyfill like [textStorage.js](https://gist.github.com/sofish/1221115) instead of throwing an error.

**Comment by geuis** [comment]
I've thought about it a while but I don't see any reason to support cookie fallback. I think that if you are developing an application that uses Argon, you can load a storage polyfill before loading this library. As long as it replicates the standard api interface, then Argon should be perfectly happy.
